name: ips
description: International Patient Summary
version: 0.1.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/ips

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  fhir_dstu2:
    path: ../fhir_dstu2
  fhir_primitives:
    path: ../fhir_primitives
  fhir_r4:
    path: ../fhir_r4
  fhir_r5: 
    path: ../fhir_r5
  fhir_r6:
    path: ../fhir_r6
  fhir_stu3:
    path: ../fhir_stu3
  fhir_yaml:
    path: ../fhir_yaml
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: 13.2.1
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  riverpod_annotation: 2.3.5
  rxdart: 0.27.7
  yaml: ^3.1.2

dependency_overrides:
  meta: ^1.12.0
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  # dart run import_sorter:main
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  riverpod_generator: 2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/images/
  - assets/samples/
