name: ips
description: International Patient Summary
version: 0.1.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/ips

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  fhir_dstu2:
    path: ../fhir_dstu2
  fhir_primitives:
    path: ../fhir_primitives
  fhir_r4:
    path: ../fhir_r4
  fhir_r5: 
    path: ../fhir_r5
  fhir_r6:
    path: ../fhir_r6
  fhir_stu3:
    path: ../fhir_stu3
  fhir_yaml:
    path: ../fhir_yaml
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  # dart run import_sorter:main
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  test: ^1.25.2
