name: server
description: Simple standalone server for serving flutter web apps, utilizing shelf, goal is full stack dart.
version: 1.3.03+1303

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  shelf_static: ^1.1.1