enum IpsSections {
  medications,
  allergies,
  problems,
  procedures,
  immunizations,
  medicationDevices,
  results,
  vitalSigns,
  pastIllnessHx,
  functionalStatus,
  planOfCare,
  socialHistory,
  pregnancyHx,
  advanceDirectives,
}
